[project]
name = "obligate"
version = "1.0.0"
description = "Utilities for enforcing contracts"
license = "BSD-4-Clause"
authors = [
    {name = "Samuel Jones",email = "sjones.nova@gmail.com"}
]
keywords = ["contracts", "runtime-validation", "precondition", "postcondition", "validation"]
dynamic = [ "classifiers" ]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[project.urls]
repository = "https://github.com/sjones5516/obligate"

[tool.poetry]
packages = [{include = "obligate", from = "src"}]

classifiers = [
    "Topic :: Software Development :: Testing"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
